spring:
  application:
    name: service-zuul

server:
  port: 8766

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    api1:
      path: /api1/**
      serviceId: service-feign
    api2:
      path: /api2/**
      serviceId: service-feign-hystrix

