spring:
  application:
    name: service-feign-hystrix

server:
  port: 8765

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    enabled: true
